### ISSUE TITLE
Why ECB?

### ISSUE THREAD

**Issue by dulac** [keeweb/kdbxweb#12]
Hi there! Could you please describe why is Electronic Codebook (ECB) simulation and ECB fallback used in kdbxweb/lib/crypto/key-encryptor.js ?

ECB does not provide strong confidentiality.

**Comment by antelle** [comment]
It's key derivation function, not encryption obe. Further questions about format design please ask on KeePass forum, not here, we are not designing storage format.

**Comment by antelle** [comment]
A bit more info: new KeePass format is not finalized yet, and any ideas are welcome. Format description: http://keepass.info/help/kb/kdbx_4.html, you can suggest them here: https://sourceforge.net/p/keepass/discussion/329220/thread/acfd14b1/
