### ISSUE TITLE
Can't open an empty database?

### ISSUE THREAD

**Issue by expiron** [keeweb/kdbxweb#15]
Hello. Today I created an empty kdbx file using code:
```js
let credentials = new kdbxweb.Credentials(kdbxweb.ProtectedValue.fromString('password'));
let db = kdbxweb.Kdbx.create(credentials, 'emptydb');
let group = db.createGroup(db.getDefaultGroup(), '1stgroup');
db.save().then(dataAsArrayBuffer => {
    fs.writeFileSync('./empty.kdbx', Buffer.from(dataAsArrayBuffer));
})
```
And then I opened it using code:
```js
let dataAsArrayBuffer = fs.readFileSync('./empty.kdbx').buffer;
let credentials = new kdbxweb.Credentials(kdbxweb.ProtectedValue.fromString('password'));
kdbxweb.Kdbx.load(dataAsArrayBuffer, credentials).then(db => {
    console.log(db);
}).catch(err => {
    console.log(err);
});
```
But it threw the error:
```js
{ [KdbxError: Error BadSignature]
  name: 'KdbxError',
  code: 'BadSignature',
  message: 'Error BadSignature' }
```
Using KeePass Password Manager or KeeWeb Online, it (kdbx file I created) can be opened normally.
Also, I have tried to create a kdbx file using KeePass whose structure like this:
```
emptydb
  |--1stgroup
  |--Recycle Bin
```
And I opened it using the code as mentioned but got the same error.
I want to know what's the meaning of 'BadSignature' and how to solve my problem.
My environment is Node.js v8.5.0 and Windows 10.

**Comment by antelle** [comment]
You cannot convert node.js Buffer to ArrayBuffer this way: when you call `.buffer`, it can return more bytes than included in node Buffer. To convert between them, you should you an array, for example. So, if you replace
```javascript
let dataAsArrayBuffer = fs.readFileSync('./empty.kdbx').buffer;
```
with
```javascript
let dataAsArrayBuffer = new Uint8Array(fs.readFileSync('./empty.kdbx')).buffer;
```
it will work.
https://nodejs.org/api/buffer.html

**Comment by expiron** [comment]
Thanks!
