### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by thardes2** [keeweb/kdbxweb#17]
I was using the version 0.4.6 until you fixed issue #16 yesterday (thank you :-)).

I noticed some changes in the performance, as the latest repository version is about three times slower than version 0.4.6:
![image](https://user-images.githubusercontent.com/6141477/30953615-f53b0330-a42c-11e7-82eb-5d382f85884f.png)

Well, three times slower is quite high :-), do you plan to improve this or is there any way to make it faster?

**Comment by antelle** [comment]
Could you please attach an example of file to check where it hangs?
Is it a complex hash function with many rounds, or the file is large?

**Comment by thardes2** [comment]
Well, unfortunately I cannot give the file I used for the screenshots above, but I created a new one, which is uploaded in this issue. 
[Temp12345.zip](https://github.com/keeweb/kdbxweb/files/1343564/Temp12345.zip)
The zip file is not encrypted, and the password for the kdbx-file is "Temp12345"

However, the effect is similar: 310 ms in version 0.4.6 and 551 ms in the latest version

**Comment by antelle** [comment]
Good catch! It turns out, TextEncoding polyfill was replacing native TextEncoder even if was supported in browser, now it's much faster, will release it later today. 🎁

**Comment by antelle** [comment]
Published v1.0.2
