### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by thardes2** [keeweb/kdbxweb#18]
KeePass databases can be compressed before being encrypted and according to KeePass, it is recommended to use the GZip compression option. 

I created a kdbx-file by using your kdbxweb library and I opened the file with the official KeePass application. The compression is enabled in the "Database Settings" of the application:
![image](https://user-images.githubusercontent.com/6141477/30953821-de84830e-a42d-11e7-8fa4-b61184c1e7f1.png)

However, I used the safe for some time and it has 15 keys stored at the moment. The size of the file is 447KB. When I open the file in KeePass, it's size is just 12 KB after saving the file without changing anything here.
So I assume there is a problem with the compression in kdbxweb. 

Note: The same problem occurs in your keeweb application, so I think this is not a problem with the way I am using your library

**Comment by antelle** [comment]
Interesting, kdbxweb is compressing files. Maybe it's because of different gzip implementations?
Are there any attachment in your kdbx file?

**Comment by thardes2** [comment]
No there are no attachments in the file. You can use the testfile from issue #17 and just save it without any changes in the official KeePass application and the file size will be much lower.

If you save the same file with keeweb, it remains the same.

**Comment by thardes2** [comment]
Well, I have additional fields in `entry.fields`, could that be a problem?

**Comment by antelle** [comment]
You have a duplicated group in your file, try to find `vw2PeELt4YlNCvnTouRuoA==` inside the xml.
Here's the XML from your actual file (kw.i.xml) and after opening it with KeePass (kp.i.xml).
[xml.zip](https://github.com/keeweb/kdbxweb/files/1345248/xml.zip)
It looks like this file was created incorrectly. How did you manage to make it?

**Comment by thardes2** [comment]
Sorry for the delay. What I do is the following: 

>  var credentials = new kdbxweb.Credentials(kdbxweb.ProtectedValue.fromString(pw), keyFileArrayBuffer);
>     var newDb = kdbxweb.Kdbx.create(credentials, username);
>     newDb.createGroup(newDb.getDefaultGroup(), 'keys');

I think this is 1:1 the part you suggest in the README

> let newDb = kdbxweb.Kdbx.create(credentials, 'My new db');
> let group = newDb.createGroup(newDb.getDefaultGroup(), 'subgroup');

**Comment by antelle** [comment]
It's not full code: it doesn't insert any entry to the db, so it's not the same thing which created the file you attached above.

**Comment by thardes2** [comment]
Sorry:
```
....
window.db = newDb;
....
function createEntry(entry){
    var group = db.getDefaultGroup();
    var dbEntry	 = window.db.createEntry(group);
    dbEntry.icon = entry.icon;
    dbEntry.fgColor = entry.fgColor;
    dbEntry.tags = entry.tags;
    dbEntry.bgColor = entry.bgColor;
    dbEntry.customIcon = entry.customIcon;
    dbEntry.fields = entry.fields;
}
```

The functions argument is create with a from displayed to the user and then copied to the object

**Comment by antelle** [comment]
Could you please upload the whole working piece of code? It's hard to debug it this way.

**Comment by thardes2** [comment]
Hi, sorry again for the delay.... However, I created a new base project and included the stuff which is necessary to reach the described behavior. 

I am using your latest release at the moment and the problem seems to be gone. I think you can close the issue here. Maybe there was an issue in your old release or fixed it when I transformed the code to the latest release.
Nevertheless, thank you for your help 👍 
[kdbxCompressionTest.zip](https://github.com/keeweb/kdbxweb/files/1368171/kdbxCompressionTest.zip)

**Comment by antelle** [comment]
I'll close this, GZip is working fine, the test is below.
I thought, maybe it's because gzip is more effective in node.js, but it's not: the same works in browser and gives 310kb as well. Re-saving the same file with KeePass gives 340kb.
If it doesn't work for you, it's because the way you use it, I don't want to debug it, sorry. Saving to XML might help.
Example:
```
const fs = require('fs');
const kdbxweb = require('kdbxweb');

const cred = new kdbxweb.Credentials(kdbxweb.ProtectedValue.fromString('test'));
const db = kdbxweb.Kdbx.create(cred, 'example');
const subGroup = db.createGroup(db.getDefaultGroup(), 'subgroup');
for (let i = 0; i < 10000; i++) {
    const entry = db.createEntry(subGroup);
    db.meta.customData.key = 'val#' + i;
    db.createDefaultGroup();
    db.createRecycleBin();
    entry.fields.Title = 'Entry #' + i;
    entry.fields.UserName = 'user';
    entry.fields.Password = kdbxweb.ProtectedValue.fromString('pass');
    entry.fields.Notes = 'notes';
    entry.fields.URL = 'url';
    entry.times.update();
}
db.save().then(ab => {
    fs.writeFileSync('/Users/Antelle/Desktop/test.kdbx', Buffer.from(ab));
});
```
Here's the resulting file:
[test.kdbx.zip](https://github.com/keeweb/kdbxweb/files/1777330/test.kdbx.zip)
