### ISSUE TITLE
Installing this package on npm throws an error

### ISSUE THREAD

**Issue by sallar** [keeweb/kdbxweb#20]
Im trying to install this package, but all I get is this error:

```
› npm i kdbxweb@latest
npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t git://github.com/keeweb/jssha.git
npm ERR!
npm ERR! fatal: remote error:
npm ERR!   Repository not found.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sallar/.npm/_logs/2018-03-03T19_24_44_180Z-debug.log
```

Thanks.

**Comment by sallar** [comment]
@antelle Hi. Thanks. I had to manually remove the old kdbxweb from package-lock.json and install it again.

**Comment by antelle** [comment]
Yes, dependencies can be there... jssha was removed in this commit from today: 70417909043214bf7d99ca739c63ba83f36a50be

**Comment by sallar** [comment]
I see. This is good. But unfortunately due to the old versions pointing to the git repo instead of a npm module, now anyone who uses an older version will see failures. I wish you'd keep the deleted repo around for a while so people have a chance to upgrade.

**Comment by antelle** [comment]
Yeah I forget about this indeed.

**Comment by antelle** [comment]
The repos are back :)
