### ISSUE TITLE
Entry.String.Value null

### ISSUE THREAD

**Issue by timendum** [keeweb/kdbxweb#21]
Hi,
I've looked at the xml genergated by kdbxweb and I found a quirk, it can produce a null Entry.String.Value if, on the web interface, I fill and then delete a Note or another field.

I think the correct ways to handle it are:

- produce an empty Value (ie `<Value></Value>`)
- or skip the whole String field.

Thanks

[Sample xml and kdbx](https://github.com/keeweb/kdbxweb/files/1974918/New-2.zip) - password "demo"

**Comment by antelle** [comment]
Hi! That's ok, other clients do it too.
