### ISSUE TITLE
kdbx4 upgrade should clear keyEncryptionRounds from header

### ISSUE THREAD

**Issue by luckyrat** [keeweb/kdbxweb#25]
To upgrade a new database I need to execute:

```
db.upgrade();
db.header.keyEncryptionRounds = undefined;
```

I think the 2nd line should be included within the upgrade function?

For example, in KeeWeb, it's used to conditionally display relevant settings:

https://github.com/keeweb/keeweb/blob/af9d668d2ae2f35c2f88bf659fdcb7c8a154b407/app/templates/settings/settings-file.hbs#L122

**Comment by antelle** [comment]
Thanks! Fixed it
