### ISSUE TITLE
kdbx version 4.1 unknown

### ISSUE THREAD

**Issue by trxa** [keeweb/kdbxweb#31]
Hi,

If I call `KdbxHeader.setVersion(4)` it sets the `versionMinor` to  `1`. I could not find any specification for a kdbx 4.**1** file format. Some apps like Strongbox check the minor version too and are therefore not able to open the databases written via kdbxweb.
I also had this problem when creating a database with keeweb.

Could you please check, whether the latest minor version for kdbx4 shouldn't be `0`?

Thanks,
trxa

**Comment by antelle** [comment]
Hi! Thanks, it should be v4.0 indeed.

**Comment by antelle** [comment]
Fixed in ac0315d26ab86b0eb987a21fc1c25fc9d8d47401
