### ISSUE TITLE
decrypt Password

### ISSUE THREAD

**Issue by lollita** [keeweb/kdbxweb#32]
how decrypt entry.fields.Password ?

**Comment by antelle** [comment]
There are several ways of doing that, depending on your needs:
- [getText](https://github.com/keeweb/kdbxweb/blob/master/lib/crypto/protected-value.js#L93)
- [getBinary](https://github.com/keeweb/kdbxweb/blob/master/lib/crypto/protected-value.js#L101)
- [getHash](https://github.com/keeweb/kdbxweb/blob/master/lib/crypto/protected-value.js#L81)

**Comment by lollita** [comment]
ty.
