### ISSUE TITLE
 Error: Can't resolve 'crypto'

### ISSUE THREAD

**Issue by TomMettam** [keeweb/kdbxweb#38]
When trying to include this project into an Angular project, it fails with:

` Error: Can't resolve 'crypto' in '..\node_modules\kdbxweb\dist'`

Is there any chance this could be made webpack compatible?

**Comment by antelle** [comment]
Hi! It's compatible with WebPack, however you need to tune your config. Probably you need to exclude `crypto`, something like this: 
```js
node: {
    crypto: false
}
```
