### ISSUE TITLE
Can't install library 

### ISSUE THREAD

**Issue by kimgysen** [keeweb/kdbxweb#40]
I would like to play around with this lib, but can't install it. 
It gets stuck here: 

C:\Users\7508594\Documents\lcm\code\keepass>npm i --save kdbxweb
[..................] \ fetchMetadata: sill resolveWithNewModule kdbxweb@1.14.1 checking installable status

I tried to install another library to see if it was a problem with my proxy, but didn't appear to be the case. 
Also it's useful to add this to the docs. 
Even though this should be obvious, to be sure I had to check the issues list to find confirmation that the installation command was correct.

**Comment by antelle** [comment]
Hi! Please paste logs with —verbose

**Comment by kimgysen** [comment]
Thanks for fast reply. Here are the logs: 

![image](https://user-images.githubusercontent.com/4547364/105989209-1435bf80-60a1-11eb-94ad-97c90cd102f7.png)

**Comment by antelle** [comment]
so, what is the error?

**Comment by antelle** [comment]
It’s an issue with your network, you can Google the line you posted.
