### ISSUE TITLE
Read unencrypted header

### ISSUE THREAD

**Issue by Maswor** [keeweb/kdbxweb#41]
Hello sir/madam

According to KDBX 4 specs at:
[https://keepass.info/help/kb/kdbx_4.html#exthdr](https://keepass.info/help/kb/kdbx_4.html#exthdrl)

> Note that the header data is not encrypted and is only present in KDBX files (not in XML exports).

I'm interested in setting a lookup table that I can read before decoding. I see that `kdbxweb` need to read the database with credentials before I can access the header. Could you guide me way to do so without logging in first. 

Thank you and best regards!

**Comment by antelle** [comment]
Hi! You can find an example here: https://github.com/keeweb/kdbxweb/blob/master/scripts/dump-header.ts
If you just need a tool that dumps this unencrypted header, you can launch it like this:
```
npm run script:dump-header my-db.kdbx
```
